// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentGateway.Models;

namespace PaymentGateway.Migrations
{
    [DbContext(typeof(PaymentContext))]
    partial class PaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentGateway.Models.Payment", b =>
                {
                    b.Property<int>("paymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<string>("cardNumber")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("cvv")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("expiryDate")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("paymentID");

                    b.ToTable("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
